#!/bin/sh

if test $# -eq 0
then
    echo
    echo "=================================="
    echo "Unset http/https proxy in terminal"
    echo "=================================="
    echo
    echo
    export http_proxy=
    export https_proxy=
    curl https://api.myip.com/
    echo
    echo
    exit
fi

echo
echo "================================"
echo "Set http/https proxy in terminal"
echo "================================ $1"
echo
echo
export http_proxy="http://$1"
export https_proxy="https://$1"
curl https://api.myip.com/
echo
echo
