#!/bin/sh
export proxyHost=$2

if [ "$proxyHost" = "" ]; then
    export proxyHost=127.0.0.1
else
    export proxyHost=$2
fi


export proxyPort=$1
if [ "$proxyPort" = "" ]; then
    echo
    echo "============================="
    echo "Unset http/https proxy in cmd"
    echo "============================="
    echo
    echo
    export http_proxy=
    export https_proxy=
    curl https://api.myip.com/
else
    export proxyHostPort="$proxyHost:$proxyPort"
    echo
    echo "==========================="
    echo "Set http/https proxy in cmd"
    echo "=========================== $proxyHostPort"
    echo
    echo
    export http_proxy=$proxyHostPort
    export https_proxy=$proxyHostPort
    export proxyHostPort=
    curl https://api.myip.com/
fi

export proxyHost=
export proxyPort=
echo
echo
